os: Visual Studio 2015

# Version format
version: 0.2.0.{build}

cache:
  - src\packages -> **\packages.config   # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

branches:
  only:
    - develop
    - file-config-multi-appenders

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX if a rtm release build this should be blank, otherwise if empty will default to alpha
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
init:
  - set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=alpha

build_script:
- build-appveyor.cmd

artifacts:
  - path: artifacts\*.nupkg
  - path: artifacts\*.zip

deploy:
     # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/umbracoazurelogger/api/v2/package
    symbol_server: https://nuget.symbolsource.org/MyGet/umbracoazurelogger
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: develop

    # Umbraco MyGet community feed
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-packages/api/v2/package
    symbol_server: https://nuget.symbolsource.org/MyGet/umbraco-packages
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: develop


    # MyGet Deployment for builds & releases
  - provider: NuGet
    server: https://www.myget.org/F/umbracoazurelogger/api/v2/package
    symbol_server: https://nuget.symbolsource.org/MyGet/umbracoazurelogger
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: file-config-multi-appenders

    # Umbraco MyGet community feed
  - provider: NuGet
    server: https://www.myget.org/F/umbraco-packages/api/v2/package
    symbol_server: https://nuget.symbolsource.org/MyGet/umbraco-packages
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: file-config-multi-appenders
